### ISSUE TITLE
Can't telnet or get Onvif

### ISSUE THREAD

**Issue by CyberCowboy** [guino/Merkury1080P#15]
Working on getting 4 of these cameras setup.   and I'm getting confirmation of root:

`mem=64M console=ttySAK0,115200n8 loglevel=10 mtdparts=spi0.0:256k(bld),64k(env),64k(enc),64k(sysflg),3m(sys),4032k(app),640k(cfg) ppsAppParts=5 ip=0 - ip=30;/mnt/mmc01/initrun.sh)&:::::;date>/tmp/hack;(sleep
`

However I can't telnet into the device on port 23  

`telnet 192.168.86.134
Connecting To 192.168.86.134...Could not open connection to the host, on port 23: Connect failed`

When I try to patch my ppsapp I get in a bootloop, so was trying what's suggested in the last reply in this post: https://www.reddit.com/r/videosurveillance/comments/kko49q/merkury_geeni_camera_rtsphome_assistant/hhg92v2/

However it requires telnet. 

Here's my device info:

`{"devname":"Smart Home Camera","model":"Mini 11S","serialno":"101542740","softwareversion":"4.0.6","hardwareversion":"M11S_A2_V10_F37","firmwareversion":"ppstrong-a3-tuya2_merkury-4.0.6.20210310","identity":"M3R0049H5601418034","authkey":"wUxefaP5KHgSU6kqoWyq6gYWzhVvC7gS","deviceid":"pp0179c2d664b2843e65","pid":"aaa","WiFi MAC":"84:7a:b6:32:e2:4e","ETH MAC":"00:00:00:00:00:00"}
`

Anything else, let me know.

**Comment by guino** [comment]
@CyberCowboy you need to check you have all mmc files in place -- for telnet you need to have the right busybox file (which is over 1Mb size) and initrun.sh, custom.sh and passwd file at a minimum. If you have all the files you should double check the IP address is correct.

I would recommend you work on getting telnet first (without a ppsapp file on the root of SD card), once that's working we can look at the boot loop issue which is usually due to a bad patch, wrong patch or corrupted ppsapp file.

Feel free to post a zip of your SD card contents (with the SDT folder) and I can check it out if you like.

**Comment by CyberCowboy** [comment]
Seems I missed the busybox replacement, Thanks Guino.
