### ISSUE TITLE
How could I go about fixing a camera focus issue

### ISSUE THREAD

**Issue by GuidoFromNY** [guino/Merkury1080P#57]
Is it possible to rotate threaded lens left or right in 1st pic below to adjust focus or is this a codec issue or some kinda of issue that can be patched or forced with update? 
![IMG-20240516-WA0003_resized](https://github.com/guino/Merkury1080P/assets/170154571/613077e6-db2c-4b1f-89a3-f4a7cee67ff2)
This second picture was after I first disassembled camera
![IMG-20240516-WA0003](https://github.com/guino/Merkury1080P/assets/170154571/4bd07245-b889-400e-82ba-6115b83ba967)
This pic below is from box of two pack I purchased and support ticket added to top right if screen shot they were supposed to give me a call back today but never heard anything.
![20240520_231535](https://github.com/guino/Merkury1080P/assets/170154571/3e56f442-eabb-4f67-b328-e143bb331522)

@guino Bought 2 of these 1 works great didnt bother trying to run only 1 out of 2 pack what would i need to do to adjust camera lens to use this. Geeni live chat was less than helpful.

_Originally posted by @guino in https://github.com/guino/Merkury1080P/issues/39#issuecomment-1249563101_

**Comment by GuidoFromNY** [comment]
![171589692199185](https://github.com/guino/Merkury1080P/assets/170154571/c520f73c-b68f-48e3-a96d-8b49aa5c70aa)

**Comment by GuidoFromNY** [comment]
https://github.com/guino/Merkury1080P/assets/170154571/61db566c-187b-48dd-af56-3ff5a58b0262

**Comment by GuidoFromNY** [comment]
Any advice or direction will be much appreciated 🫱🏻‍🫲🏽

**Comment by guino** [comment]
@GuidoFromNY This looks totally like a hardware issue, lens may be mounted incorrectly, have cloudiness, have some manufacturing defect altogether or even something silly like one of the protector films may have been left in place. If you bought it recently you may be able to take it back to the store and just 'exchange' it for another of the same model. I bought a Merkury 1080P from Walmart once that stopped working and I just took it back for an exchange, it was a pretty simple process, but depends on the store and how long you've had it.

**Comment by GuidoFromNY** [comment]
I bought this like 3 or 4 years ago in two pack cam set could never get 2nd cam to pair I forgot about cam wife must have hidden box out of way i found it got paired via wifi/blutooth found out was blurry walmart wont take electronics returns after this long geeni wont let me know what i can do or they can fix i took apart to check for issues but seen nothin that stood out gotten quality a lil better by putting solid gray image in front of lens and switching from sd to hd to ir but i think i need to remove glue and manual adjust lens on the camera the other that came with it has been mounted outside for years lol (yes I know its a indoor cam) because at the time we had people stealin sh*t outside so I needed it buf for price this thing is a champ been outside in snow rain sun and never really had issues with any but this one.

**Comment by GuidoFromNY** [comment]
![Resized_20240527_144533_1716835828382](https://github.com/guino/Merkury1080P/assets/170154571/b4dd11ef-97eb-4967-92eb-b59a34893913)

**Comment by guino** [comment]
@GuidoFromNY sorry to hear of your issues. Honestly I'm worried even about your 1st (working) camera because you seem to have mounted it outdoor but I believe this is an indoor camera model. If it's been a few years I doubt they even manufacture these anymore so it would be unlikely they would be willing (or able) to replace the device at this point in time. My advice is to always test any device you buy immediately (or at least before warranty runs out), I always unpack carefully and test anything so I can return it right away if needed, then if I don't need all items at once I'll store it knowing they were at least working when I purchased them.

If you took it apart and checked the front and back of the lens module, and the board sensor for any plastic film and there's nothing visible, you can check if you can disassemble the lens module itself (check for screws etc). Unfortunately the amount of time you may spend on this may cost you as much as just buying a similar new device. You could keep this one as 'spare parts' for the working one in case/when if fails you could swap parts to try and fix it, but not much else you can do.

**Comment by GuidoFromNY** [comment]
>@guino Honestly i have 4 of geeni cw017 all of them been mounted outside for years these and 2 of piece of shit white merkury cw217. Honestly if u ask me the Geeni smart indoor cams cw017 ones are better then white indoor ones and the geeni app is better all around. 
![20240527_155719](https://github.com/guino/Merkury1080P/assets/170154571/476c0c94-7046-47ef-a860-44106357d7e5)
![20240527_155742](https://github.com/guino/Merkury1080P/assets/170154571/d8a921b6-3e7e-4da4-a13d-1a1061df8468)

>@guino I appreciate your feed back finding your post inspired me got me excited & dip my toe into learning coding. But Im going to take apart again and adjust lens then reglue threads I found a forum thread on a security cam forum about upscaling lenses and or replacing them i dont mind takingit apart as far as time spent. i take shit apart and fix for shits and giggles when I'm bored.

**Comment by GuidoFromNY** [comment]
>@guino Thanks again for your reply and suggestions just glad I found this thread & all you guys been doing with the cameras in this section of github 🖥💻⌨️ 👾🫱🏻‍🫲🏽🤜🏼🤛🏼🙋🏻👋🏼👾
